# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos: 
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort - Sort Python imports (auto-fixes)
        types: [cython, pyi, python]
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 22.3.0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        name: black - consistent Python code formatting (auto-fixes)
        language_version: python # Should be a command that runs python3.6+
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: flake8 - Python linting
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
      - id: nbqa-isort
        name: nbqa-isort - Sort Python imports (notebooks; auto-fixes)
        # strangely the args need to be concatenated
        args: ["--profile=black"]
      - id: nbqa-black
        name: nbqa-black - consistent Python code formatting (notebooks; auto-fixes)
        additional_dependencies: [black==22.3.0]
      # TODO: Disabled for now until it's clear how to add noqa to specific cells of a Jupyter notebook
      #- id: nbqa-flake8
      #  name: nbqa-flake8 - Python linting (notebooks)
      #  additional_dependencies: [ flake8==3.9.2 ]
  #- repo: https://github.com/s-weigand/flake8-nb
  #  rev: 0.5.2
  #  hooks:
  #  - id: flake8-nb
